name: libsodiumIssue
version: 0.0.1
synopsis: A problem with libsodium bindings
maintainer: 5ndg
license: AllRightsReserved

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - base16-bytestring

extra-libraries: sodium

executables:
  main:
    main: Main.hs
    ghc-options: -Wall -O2 -threaded
    source-dirs: .
